### ISSUE TITLE
version for emacs-compat needs to be bumped up

### ISSUE THREAD

**Issue by mbkamble** [babariviere/guix-emacs#3]
I am a relative noob to guix. I have included this channel in my channels.scm configuration file. After a `guix pull`, when I try to build a new profile using a manifest file, I get the error:
```
building /gnu/store/kwyjfizv5w6v3iav07wq39kivilsd6a8-compat-28.1.1.0.tar.drv...
|builder for `/gnu/store/kwyjfizv5w6v3iav07wq39kivilsd6a8-compat-28.1.1.0.tar.drv' failed to produce output path `/gnu/store/j71cjf90hhmkf0ik01wx0ylzsj7v5b7s-compat-28.1.1.0.tar'
build of /gnu/store/kwyjfizv5w6v3iav07wq39kivilsd6a8-compat-28.1.1.0.tar.drv failed
View build log at '/var/log/guix/drvs/kw/yjfizv5w6v3iav07wq39kivilsd6a8-compat-28.1.1.0.tar.drv.gz'.
```

compat-28.1.1.0 has been archived and replaced by 28.1.1.1 at https://elpa.gnu.org/packages/compat.html
So the pakage definition of emacs-compat in emacs/packages/elpa.scm needs to be updated

**Comment by babariviere** [comment]
I have bumped it in commit 6815af364c4652afc368d562f972ed87c083f76a, thanks!
