### ISSUE TITLE
Running M-x vterm after installing emacs-vterm, asks to compile vterm-module, which fails

### ISSUE THREAD

**Issue by mekeor** [babariviere/guix-emacs#4]
- Install `emacs` and `emacs-vterm`.
- Run `emacs` and type `M-x vterm RET`.
- A prompt will ask: `Vterm needs \`vterm-module\` to work. Compile it now?`
- Respond with `yes`.
- This message will be reported: `vterm-module--cmake-is-available: Vterm needs CMake to be compiled.  Please, install CMake`.

Is this supposed to work this way? I thought maybe the vterm-module will be installed in compiled form.

**Comment by babariviere** [comment]
Hello,
No, it's not supposed to work this way! They may have changed the way they build vterm. I will take a look at this!

**Comment by mekeor** [comment]
Thanks.

I also tried to install cmake into my user profile and compiling vterm-module but it resulted in another error.

**Comment by babariviere** [comment]
Ok, it's totally my fault!

It's fixed on master if you want the latest patch.
