### ISSUE TITLE
License and copyright references

### ISSUE THREAD

**Issue by mekeor** [babariviere/guix-emacs#5]
- There is no LICENSE file for this repository and not all files do have a header specifying a license.
- the `/emacs/packages/melpa.scm` contains code which clearly has been copied from the official GNU Guix repository's `gnu/packages/emacs-xyz.scm` without copying the list of copyright owners.

**Comment by babariviere** [comment]
Sure, you are right.

For the first part, I guess I have to use GPL-3 since that's what Guix use?

On the second part, what part of the header should I copy?
Should I copy this part too?

```
This file is part of GNU Guix.
```

Even if it's not really part of Guix?

**Comment by babariviere** [comment]
I have added the GPLv3 license and the copyright at the top of `melpa.scm`.
Tell me if it looks good to you!

**Comment by mekeor** [comment]
yes, that looks good to me.

btw, you might want to adapt the `Reproducible development environment` description in the first line.

**Comment by babariviere** [comment]
Oups you are right thanks.
